parameters:
- name: appVersion
  type: string
- name: dockerHubID
  type: string
- name: dockerRepo
  type: string

stages:
- stage: StageID_BuildAndPushDockerImage
  displayName: 'Docker: Build and Push'
  dependsOn: StageID_BuildAndTestProject
  condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'main'))
  jobs:
  - job: JobID_BuildAndPushDockerImage
    variables:
      VER: ${{ parameters.appVersion }}
    steps:
    - checkout: self
    - task: Docker@2
      displayName: 'Build'
      inputs:
        containerRegistry: 'DockerHubConnection'
        repository: '${{ parameters.dockerHubID }}/${{ parameters.dockerRepo }}'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(VER)
    - script: |
        mkdir -p "$(Build.ArtifactStagingDirectory)/DockerImage"
        LAST_ID=$(docker images -q | head -n 1)
        docker save "$LAST_ID" -o "$(Build.ArtifactStagingDirectory)/DockerImage/image.tar"
      displayName: 'Save Docker image to tar'
    - task: PublishPipelineArtifact@1
      displayName: 'Artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/DockerImage/image.tar'
        artifact: 'DockerImage_$(VER)'
    - task: Docker@2
      displayName: 'Push'
      inputs:
        containerRegistry: 'DockerHubConnection'
        repository: '${{ parameters.dockerHubID }}/${{ parameters.dockerRepo }}'
        command: 'push'
        tags: |
          $(VER)
