parameters:
- name: ciTemplates
  type: string
- name: dockerId
  type: string
- name: dockerRepo
  type: string
- name: dockerToken
  type: string

stages:
- stage: StageID_PreBuild
  displayName: 'Pre-Build'
  jobs:
  - job: JobID_PreBuild
    displayName: 'Pre-Build Analysis'
    steps:
    - checkout: self
    - [cite_start]checkout: ${{ parameters.ciTemplates }}

    - script: |
        # Використовуємо шлях з параметром [cite: 177]
        source $(Build.SourcesDirectory)/${{ parameters.ciTemplates }}/common-scripts/logging.sh
        source $(Build.SourcesDirectory)/${{ parameters.ciTemplates }}/common-scripts/dockerhub.sh
        
        if [ -z "$(MANUALLY_SETUP_APP_VERSION)" ]; then
          NEW_VER=$(get_docker_image_latest_version "${{ parameters.dockerRepo }}" "${{ parameters.dockerId }}" "${{ parameters.dockerToken }}")
          NEW_VER=$(echo $NEW_VER | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
        else
          NEW_VER="$(MANUALLY_SETUP_APP_VERSION)"
        fi
        echo "##vso[task.setvariable variable=APP_VERSION;isOutput=true]$NEW_VER"
      name: CalculateAppVersion
      displayName: 'Calculate Application Version'
