parameters:
- name: ciTemplatesRepo
  type: string

stages:
- stage: StageID_PreBuild
  displayName: 'Pre-Build'
  jobs:
  - job: JobID_PreBuild
    steps:
    - checkout: self
    - checkout: ${{ parameters.ciTemplatesRepo }}
    - script: |
        source $(Build.SourcesDirectory)/${{ parameters.ciTemplatesRepo }}/common-scripts/dockerhub.sh
        NEW_VER=$(get_docker_image_latest_version "1.0.5")
        echo "##vso[task.setvariable variable=APP_VERSION;isOutput=true]$NEW_VER"
      name: CalculateAppVersion
