parameters:
- name: appVersion
  type: string

stages:
- stage: StageID_BuildAndTestProject
  displayName: 'Project: Build and Test'
  dependsOn: StageID_PreBuild
  jobs:
  - job: JobID_BuildAndTest
    variables:
      VERSION: ${{ parameters.appVersion }}
    steps:
    - script: |
        pip install -r users-api/requirements.txt
        pip install pytest pytest-azurepipelines httpx
        
        export PYTHONPATH=$PYTHONPATH:$(pwd)/users-api/src
        
        pytest users-api/tests --junitxml=$(System.DefaultWorkingDirectory)/test-results.xml
      displayName: 'Run Unit Tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results.xml'
        mergeTestResults: true
        failTaskOnFailedTests: true
      displayName: 'Publish Unit Test Report'
