parameters:
- name: appVersion
  type: string

stages:
- stage: StageID_BuildAndTestProject
  displayName: 'Project: Build and Test'
  dependsOn: StageID_PreBuild
  jobs:
  - job: JobID_BuildAndTest
    displayName: 'Build and Test'
    variables:
      VERSION: ${{ parameters.appVersion }}
    steps:
    - script: |
        pip install -r users-api/requirements.txt
        echo "Project builds successfully. Unit tests skipped for this demo."
      displayName: 'Build project'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(System.DefaultWorkingDirectory)/test-results.xml'
        mergeTestResults: true
        failTaskOnFailedTests: true
      displayName: 'Publish Unit Test Report'
