parameters:
- name: appVersion
  type: string

stages:
- stage: StageID_BuildAndTestProject
  displayName: 'Project: Build and Test'
  dependsOn: StageID_PreBuild
  jobs:
  - job: JobID_BuildAndTest
    displayName: 'Build and Test'
    variables:
      VERSION: ${{ parameters.appVersion }}
    steps:
    - script: |
        cd users-api
        
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-azurepipelines httpx fastapi
        
        python -m pytest tests/ --junitxml=../test-results.xml
      displayName: 'Run Unit Tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/test-results.xml'
        mergeTestResults: true
        failTaskOnFailedTests: true
      displayName: 'Publish Unit Test Report'
